//
//  LanguageColor.swift
//  GitHubFollowers
//
//  Created by joaovitor on 24/03/22.
//

import Foundation
import UIKit

typealias LanguageColors = [String: UIColor?]

struct Language {
    static let colors: LanguageColors = [
        "Mercury": UIColor(hex: "#ff2b2b"),
        "TypeScript": UIColor(hex: "#2b7489"),
        "PureBasic": UIColor(hex: "#5a6986"),
        "Objective-C++": UIColor(hex: "#6866fb"),
        "Self": UIColor(hex: "#0579aa"),
        "edn": UIColor(hex: "#db5855") ,
        "NewLisp": UIColor(hex: "#87AED7"),
        "Jupyter Notebook": UIColor(hex: "#DA5B0B"),
        "Rebol": UIColor(hex: "#358a5b"),
        "Frege": UIColor(hex: "#00cafe"),
        "Dart": UIColor(hex: "#00B4AB"),
        "AspectJ": UIColor(hex: "#a957b0"),
        "Shell": UIColor(hex: "#89e051"),
        "Web Ontology Language": UIColor(hex: "#9cc9dd"),
        "xBase": UIColor(hex: "#403a40"),
        "Eiffel": UIColor(hex: "#946d57"),
        "Nix": UIColor(hex: "#7e7eff"),
        "RAML": UIColor(hex: "#77d9fb"),
        "MTML": UIColor(hex: "#b7e1f4"),
        "Racket": UIColor(hex: "#22228f"),
        "Elixir": UIColor(hex: "#6e4a7e"),
        "SAS": UIColor(hex: "#B34936") ,
        "Agda": UIColor(hex: "#315665"),
        "wisp":UIColor(hex: "#7582D1"),
        "D": UIColor(hex: "#ba595e"),
        "Kotlin": UIColor(hex: "#F18E33"),
        "Opal": UIColor(hex: "#f7ede0"),
        "Crystal": UIColor(hex: "#776791"),
        "Objective-C": UIColor(hex: "#438eff"),
        "C": UIColor(hex: "#555555"),
        "C++": UIColor(hex: "#f34b7d"),
        "ColdFusion CFC": UIColor(hex: "#ed2cd6"),
        "Oz": UIColor(hex: "#fab738"),
        "Mirah": UIColor(hex: "#c7a938"),
        "Objective-J": UIColor(hex: "#ff0c5a"),
        "Gosu": UIColor(hex: "#82937f"),
        "FreeMarker": UIColor(hex: "#0050b2"),
        "Ruby": UIColor(hex: "#701516"),
        "Component Pascal": UIColor(hex: "#b0ce4e"),
        "Arc": UIColor(hex: "#aa2afe"),
        "Brainfuck":UIColor(hex: "#2F2530"),
        "Nit": UIColor(hex: "#009917"),
        "APL": UIColor(hex: "#5A8164"),
        "Go": UIColor(hex: "#375eab"),
        "Visual Basic": UIColor(hex: "#945db7"),
        "PHP": UIColor(hex: "#4F5D95"),
        "Cirru": UIColor(hex: "#ccccff"),
        "SQF": UIColor(hex: "#3F3F3F"),
        "Glyph": UIColor(hex: "#e4cc98"),
        "Java": UIColor(hex: "#b07219"),
        "MAXScript": UIColor(hex: "#00a6a6"),
        "Scala": UIColor(hex: "#DC322F"),
        "Makefile": UIColor(hex: "#427819"),
        "ColdFusion": UIColor(hex: "#ed2cd6"),
        "Perl": UIColor(hex: "#0298c3"),
        "Lua": UIColor(hex: "#000080"),
        "Vue": UIColor(hex: "#2c3e50"),
        "Verilog": UIColor(hex: "#b2b7f8"),
        "Factor": UIColor(hex: "#636746"),
        "Haxe": UIColor(hex: "#df7900"),
        "Pure Data":UIColor(hex: "#91de79"),
        "Forth":UIColor(hex: "#341708"),
        "Red": UIColor(hex: "#ee0000"),
        "Hy": UIColor(hex: "#7790B2"),
        "Volt": UIColor(hex: "#1F1F1F"),
        "LSL": UIColor(hex: "#3d9970"),
        "eC": UIColor(hex: "#913960"),
        "CoffeeScript": UIColor(hex: "#244776"),
        "HTML": UIColor(hex: "#e44b23"),
        "Lex": UIColor(hex: "#DBCA00"),
        "API Blueprint": UIColor(hex: "#2ACCA8"),
        "Swift": UIColor(hex: "#ffac45"),
        "AutoHotkey": UIColor(hex: "#6594b9"),
        "Isabelle": UIColor(hex: "#FEFE00"),
        "Metal": UIColor(hex: "#8f14e9"),
        "Clarion": UIColor(hex: "#db901e"),
        "JSONiq": UIColor(hex: "#40d47e"),
        "Boo": UIColor(hex: "#d4bec1"),
        "AutoIt": UIColor(hex: "#1C3552"),
        "Clojure": UIColor(hex: "#db5855"),
        "Rust": UIColor(hex: "#dea584"),
        "Prolog": UIColor(hex: "#74283c"),
        "SourcePawn":UIColor(hex: "#5c7611"),
        "AMPL": UIColor(hex: "#E6EFBB"),
        "FORTRAN": UIColor(hex: "#4d41b1"),
        "ANTLR": UIColor(hex: "#9DC3FF"),
        "Harbour": UIColor(hex: "#0e60e3"),
        "Tcl": UIColor(hex: "#e4cc98"),
        "BlitzMax":UIColor(hex: "#cd6400"),
        "PigLatin":UIColor(hex: "#fcd7de"),
        "Lasso": UIColor(hex: "#999999"),
        "ECL": UIColor(hex: "#8a1267"),
        "VHDL": UIColor(hex: "#adb2cb"),
        "Elm": UIColor(hex: "#60B5CC"),
        "Propeller Spin":UIColor(hex: "#7fa2a7"),
        "X10": UIColor(hex: "#4B6BEF"),
        "IDL": UIColor(hex: "#a3522f"),
        "ATS": UIColor(hex: "#1ac620"),
        "Ada": UIColor(hex: "#02f88c"),
        "Unity3D Asset": UIColor(hex: "#ab69a1"),
        "Nu": UIColor(hex: "#c9df40"),
        "LFE": UIColor(hex: "#004200"),
        "SuperCollider": UIColor(hex: "#46390b"),
        "Oxygene": UIColor(hex: "#cdd0e3"),
        "ASP": UIColor(hex: "#6a40fd"),
        "Assembly": UIColor(hex: "#6E4C13"),
        "Gnuplot": UIColor(hex: "#f0a9f0"),
        "JFlex": UIColor(hex: "#DBCA00"),
        "NetLinx": UIColor(hex: "#0aa0ff"),
        "Turing": UIColor(hex: "#45f715"),
        "Vala": UIColor(hex: "#fbe5cd"),
        "Processing": UIColor(hex: "#0096D8"),
        "Arduino": UIColor(hex: "#bd79d1"),
        "FLUX": UIColor(hex: "#88ccff"),
        "NetLogo": UIColor(hex: "#ff6375"),
        "C Sharp": UIColor(hex: "#178600"),
        "C#": UIColor(hex: "#178600"),
        "CSS": UIColor(hex: "#563d7c"),
        "Emacs Lisp": UIColor(hex: "#c065db"),
        "Stan": UIColor(hex: "#b2011d"),
        "SaltStack": UIColor(hex: "#646464"),
        "QML": UIColor(hex: "#44a51c"),
        "Pike": UIColor(hex: "#005390"),
        "LOLCODE": UIColor(hex: "#cc9900"),
        "ooc": UIColor(hex: "#b0b77e"),
        "Handlebars": UIColor(hex: "#01a9d6"),
        "J": UIColor(hex: "#9EEDFF"),
        "Mask": UIColor(hex: "#f97732"),
        "EmberScript": UIColor(hex: "#FFF4F3"),
        "TeX": UIColor(hex: "#3D6117"),
        "Nemerle": UIColor(hex: "#3d3c6e"),
        "KRL": UIColor(hex: "#28431f"),
        "Ren'Py": UIColor(hex: "#ff7f7f"),
        "Unified Parallel C": UIColor(hex: "#4e3617"),
        "Golo": UIColor(hex: "#88562A"),
        "Fancy": UIColor(hex: "#7b9db4"),
        "OCaml": UIColor(hex: "#3be133"),
        "Shen": UIColor(hex: "#120F14"),
        "Pascal": UIColor(hex: "#b0ce4e"),
        "F#": UIColor(hex: "#b845fc"),
        "Puppet": UIColor(hex: "#302B6D"),
        "ActionScript": UIColor(hex: "#882B0F"),
        "Diff": UIColor(hex: "#88dddd"),
        "Ragel in Ruby Host": UIColor(hex: "#9d5200"),
        "Fantom": UIColor(hex: "#dbded5"),
        "Zephir": UIColor(hex: "#118f9e"),
        "Click": UIColor(hex: "#E4E6F3"),
        "Smalltalk": UIColor(hex: "#596706"),
        "DM": UIColor(hex: "#447265"),
        "Ioke": UIColor(hex: "#078193"),
        "PogoScript": UIColor(hex: "#d80074"),
        "LiveScript": UIColor(hex: "#499886"),
        "JavaScript": UIColor(hex: "#f1e05a"),
        "VimL": UIColor(hex: "#199f4b"),
        "PureScript": UIColor(hex: "#1D222D"),
        "ABAP": UIColor(hex: "#E8274B"),
        "Matlab": UIColor(hex: "#bb92ac"),
        "Slash": UIColor(hex: "#007eff"),
        "R": UIColor(hex: "#198ce7"),
        "Erlang": UIColor(hex: "#B83998"),
        "Pan": UIColor(hex: "#cc0000"),
        "LookML": UIColor(hex: "#652B81"),
        "Eagle": UIColor(hex: "#814C05"),
        "Scheme": UIColor(hex: "#1e4aec"),
        "PLSQL": UIColor(hex: "#dad8d8"),
        "Python": UIColor(hex: "#3572A5"),
        "Max": UIColor(hex: "#c4a79c"),
        "Common Lisp": UIColor(hex: "#3fb68b"),
        "Latte": UIColor(hex: "#A8FF97"),
        "XQuery": UIColor(hex: "#5232e7"),
        "Omgrofl": UIColor(hex: "#cabbff"),
        "XC": UIColor(hex: "#99DA07"),
        "Nimrod": UIColor(hex: "#37775b"),
        "SystemVerilog": UIColor(hex: "#DAE1C2"),
        "Chapel": UIColor(hex: "#8dc63f"),
        "Groovy": UIColor(hex: "#e69f56"),
        "Dylan": UIColor(hex: "#6c616e"),
        "E": UIColor(hex: "#ccce35"),
        "Parrot": UIColor(hex: "#f3ca0a"),
        "Grammatical Framework": UIColor(hex: "#79aa7a"),
        "Game Maker Language": UIColor(hex: "#8fb200"),
        "Papyrus": UIColor(hex: "#6600cc"),
        "NetLinx+ERB": UIColor(hex: "#747faa"),
        "Clean": UIColor(hex: "#3F85AF"),
        "Alloy": UIColor(hex: "#64C800"),
        "Squirrel": UIColor(hex: "#800000"),
        "PAWN": UIColor(hex: "#dbb284"),
        "UnrealScript": UIColor(hex: "#a54c4d"),
        "Standard ML": UIColor(hex: "#dc566d"),
        "Slim": UIColor(hex: "#ff8f77"),
        "Perl6": UIColor(hex: "#0000fb"),
        "Julia": UIColor(hex: "#a270ba"),
        "Haskell": UIColor(hex: "#29b544"),
        "NCL": UIColor(hex: "#28431f"),
        "Io": UIColor(hex: "#a9188d"),
        "Rouge": UIColor(hex: "#cc0088"),
        "cpp": UIColor(hex: "#f34b7d"),
        "AGS Script": UIColor(hex: "#B9D9FF"),
        "Dogescript": UIColor(hex: "#cca760"),
        "nesC": UIColor(hex: "#94B0C7"),
        "Dockerfile": UIColor(hex: "#384d54")
    ]
}

